'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useUi } from '@/components/ui-provider';
import { ArrowLeft, Check, Eye, EyeOff, LockKeyhole, Mail, MapPin, UserRound } from 'lucide-react';

export default function LoginPage() {
  useEffect(() => {
    if (sessionStorage.getItem('akola-onboarding') !== 'complete') window.location.replace('/boas-vindas');
  }, []);
  const [registering, setRegistering] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState('demo@useakola.app'); const [password, setPassword] = useState('akola123'); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const { login, register } = useUi(); const router = useRouter();
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { if (registering) await register(name, email, password); else await login(email, password); router.push('/perfil'); } catch (cause) { const message = (cause as { response?: { data?: { error?: string } } }).response?.data?.error; setError(message ?? 'Não foi possível entrar. Tente novamente.'); } finally { setLoading(false); } }
  return <main className="relative min-h-screen overflow-hidden bg-akola-brand">
    <div aria-hidden="true" className="absolute -left-20 top-24 h-64 w-64 rounded-full border border-white/10" /><div aria-hidden="true" className="absolute -left-8 top-36 h-44 w-44 rounded-full border border-white/10" /><div aria-hidden="true" className="absolute right-[13%] top-[13%] h-12 w-12 rounded-full bg-akola-water shadow-[0_0_0_10px_rgba(255,255,255,.05)]" /><div aria-hidden="true" className="absolute left-[18%] top-[25%] h-9 w-9 rounded-full bg-akola-toilet" /><div aria-hidden="true" className="absolute right-[28%] top-[34%] h-8 w-8 rounded-full bg-akola-success" />
    <div className="relative mx-auto grid min-h-screen w-full max-w-6xl lg:grid-cols-[1fr_480px] lg:items-center lg:gap-16 lg:px-10 lg:py-10">
      <section className="px-6 pb-10 pt-6 text-white sm:px-10 lg:p-0">
        <Link href="/" aria-label="Voltar ao início" className="inline-grid h-11 w-11 place-items-center rounded-full border border-white/20 bg-white/10 backdrop-blur"><ArrowLeft size={19} /></Link>
        <div className="mx-auto mt-10 max-w-md text-center lg:mx-0 lg:mt-24 lg:text-left"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs font-medium text-white/85"><MapPin size={14} />Seu ponto de apoio na cidade</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.04em] sm:text-6xl">Akolá</h1><p className="mt-3 text-[18px] leading-7 text-white/90">Encontre lugares onde você é bem-vindo.</p><div className="mt-8 hidden grid-cols-3 gap-3 lg:grid"><div className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><Check size={18} /><p className="mt-3 text-sm font-medium">Informação recente</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><MapPin size={18} /><p className="mt-3 text-sm font-medium">Pontos próximos</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><UserRound size={18} /><p className="mt-3 text-sm font-medium">Comunidade ativa</p></div></div></div>
      </section>
      <section className="mt-auto rounded-t-[32px] bg-white px-6 pb-8 pt-5 shadow-[0_-16px_50px_rgba(23,33,31,.18)] sm:mx-6 sm:mb-6 sm:rounded-[30px] sm:p-8 lg:m-0">
        <div className="mx-auto mb-5 h-1 w-10 rounded-full bg-akola-border lg:hidden" />
        <div className="mb-7 grid grid-cols-2 rounded-[14px] bg-akola-soft p-1"><button type="button" onClick={() => { setRegistering(false); setError(''); }} className={`h-11 rounded-[11px] text-sm font-semibold transition ${!registering ? 'bg-white text-akola-brand shadow-sm' : 'text-akola-muted'}`}>Entrar</button><button type="button" onClick={() => { setRegistering(true); setError(''); }} className={`h-11 rounded-[11px] text-sm font-semibold transition ${registering ? 'bg-white text-akola-brand shadow-sm' : 'text-akola-muted'}`}>Criar conta</button></div>
        <h2 className="text-[28px] font-semibold tracking-tight text-akola-text">{registering ? 'Faça parte da rede' : 'Que bom ter você aqui'}</h2><p className="mt-2 text-sm leading-6 text-akola-muted">{registering ? 'Salve pontos, contribua e ajude outras pessoas na cidade.' : 'Acesse seus favoritos, contribuições e benefícios.'}</p>
        <form onSubmit={submit} className="mt-6 space-y-4">{registering && <label className="block"><span className="mb-2 block text-sm font-medium">Nome</span><div className="flex h-[54px] items-center gap-3 rounded-[14px] border border-akola-border px-4 focus-within:border-akola-brand focus-within:ring-4 focus-within:ring-akola-brand/10"><UserRound size={18} className="shrink-0 text-akola-muted" /><input required value={name} onChange={(event) => setName(event.target.value)} className="min-w-0 flex-1 bg-transparent !text-base outline-none" placeholder="Como podemos chamar você?" /></div></label>}<label className="block"><span className="mb-2 block text-sm font-medium">E-mail</span><div className="flex h-[54px] items-center gap-3 rounded-[14px] border border-akola-border px-4 focus-within:border-akola-brand focus-within:ring-4 focus-within:ring-akola-brand/10"><Mail size={18} className="shrink-0 text-akola-muted" /><input required value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" className="min-w-0 flex-1 bg-transparent !text-base outline-none" placeholder="voce@email.com" /></div></label><label className="block"><span className="mb-2 flex items-center justify-between text-sm font-medium"><span>Senha</span>{!registering && <button type="button" onClick={() => setError('A recuperação de senha será enviada quando o serviço de e-mail estiver conectado.')} className="text-xs font-semibold text-akola-brand">Esqueci minha senha</button>}</span><div className="flex h-[54px] items-center gap-3 rounded-[14px] border border-akola-border px-4 focus-within:border-akola-brand focus-within:ring-4 focus-within:ring-akola-brand/10"><LockKeyhole size={18} className="shrink-0 text-akola-muted" /><input required minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? 'text' : 'password'} autoComplete={registering ? 'new-password' : 'current-password'} className="min-w-0 flex-1 bg-transparent !text-base outline-none" placeholder="Mínimo de 6 caracteres" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Ocultar senha' : 'Mostrar senha'} className="grid h-9 w-9 shrink-0 place-items-center rounded-full text-akola-muted hover:bg-akola-soft">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p role="alert" className="rounded-[12px] bg-[#FCEEEE] p-3 text-sm text-akola-danger">{error}</p>}<button disabled={loading} className="h-[52px] w-full rounded-[14px] bg-akola-brand px-4 text-sm font-semibold text-white shadow-[0_8px_20px_rgba(14,92,87,.2)] transition hover:bg-[#0B4E49] disabled:opacity-60">{loading ? 'Aguarde...' : registering ? 'Criar minha conta' : 'Entrar no Akolá'}</button></form>
        <div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-akola-border" /><span className="text-xs text-akola-muted">ou</span><span className="h-px flex-1 bg-akola-border" /></div><Link href="/" className="flex h-[50px] items-center justify-center rounded-[14px] border border-akola-border text-sm font-semibold text-akola-text transition hover:bg-akola-soft">Continuar sem entrar</Link><p className="mt-5 text-center text-[11px] leading-5 text-akola-muted">Ao continuar, você concorda com os Termos de Uso e a Política de Privacidade.</p>
      </section>
    </div>
  </main>;
}
