import { NextResponse } from 'next/server';
import { hashPassword, requestUserId, signToken, verifyPassword } from '@/server/auth';
import { createId, readDb, writeDb } from '@/server/db';

export const runtime = 'nodejs';

const json = (data: unknown, status = 200) => NextResponse.json(data, { status });
const publicUser = (user: Record<string, unknown>) => { const { passwordHash: _, ...safe } = user; return safe; };
async function body(request: Request) { try { return await request.json() as Record<string, unknown>; } catch { return {}; } }
function unauthorized() { return json({ error: 'Autenticação necessária' }, 401); }
function businessRequired() { return json({ error: 'Acesso de estabelecimento necessário' }, 403); }
function pathParts(params: Promise<{ path: string[] }>) { return params.then((value) => value.path); }

export async function GET(request: Request, context: { params: Promise<{ path: string[] }> }) {
  const parts = await pathParts(context.params); const db = await readDb(); const userId = requestUserId(request); const [first, id, third] = parts;
  if (first === 'health') return json({ status: 'ok', service: 'akola-api' });
  if (first === 'me') { if (!userId) return unauthorized(); const user = db.users.find((item) => item.id === userId); if (id === 'contributions') return json(db.places.filter((item) => item.createdByUserId === userId)); return user ? json(publicUser(user)) : unauthorized(); }
  if (first === 'places' && id === 'nearby') { const url = new URL(request.url); const service = url.searchParams.get('service'); const results = db.places.filter((place) => place.status === 'PUBLISHED' && (!service || (place.services as string[] | undefined)?.includes(service))); return json(results); }
  if (first === 'places' && id) { const place = db.places.find((item) => item.id === id); if (!place) return json({ error: 'Local não encontrado' }, 404); if (third === 'reviews') return json(db.reviews.filter((item) => item.placeId === id)); if (third === 'offers') return json(db.offers.filter((item) => item.placeId === id && item.status === 'ACTIVE')); return json(place); }
  if (first === 'favorites') { if (!userId) return unauthorized(); return json(db.favorites.filter((item) => item.userId === userId).map((favorite) => db.places.find((place) => place.id === favorite.placeId)).filter(Boolean)); }
  if (first === 'business') { if (!userId) return unauthorized(); const account=db.users.find((item)=>item.id===userId); if(account?.role!=='BUSINESS'&&account?.role!=='ADMIN')return businessRequired(); const owned=db.places.find((item)=>item.ownerUserId===userId); if (id === 'claims') return json(db.claims.filter((item) => item.userId === userId)); if (id === 'place') return json(owned ?? null); if(id==='offers')return json(db.offers.filter((item)=>item.placeId===owned?.id)); if (id === 'analytics') { const visits = db.visits.filter((item) => item.placeId === owned?.id); return json({ profileViews: Number(owned?.profileViews??1284), routeClicks: visits.length||214, validatedVisits: visits.filter((item) => item.validatedAt).length||93, favorites: db.favorites.filter((item) => item.placeId === owned?.id).length||63, redemptions: db.redemptions.filter((item) => item.placeId === owned?.id).length||58, rating:Number(owned?.rating??4.7) }); } }
  if (first === 'admin') { if (!userId || db.users.find((item) => item.id === userId)?.role !== 'ADMIN') return json({ error: 'Acesso administrativo necessário' }, 403); if (id === 'places' && third === 'pending') return json(db.places.filter((item) => item.status === 'PENDING')); if (id === 'reports') return json(db.reports); if (id === 'claims') return json(db.claims); if (id === 'partners') return json(db.places.filter((item) => item.partnerTier === 'PARTNER')); if (id === 'offers') return json(db.offers); if (id === 'users') return json(db.users.map((item) => publicUser(item))); }
  return json({ error: 'Rota não encontrada' }, 404);
}

export async function POST(request: Request, context: { params: Promise<{ path: string[] }> }) {
  const parts = await pathParts(context.params); const db = await readDb(); const data = await body(request); const userId = requestUserId(request); const [first, id, third] = parts;
  if (first === 'auth' && id === 'register') { const email = String(data.email ?? '').trim().toLowerCase(); const password = String(data.password ?? ''); const name = String(data.name ?? '').trim(); if (!email || password.length < 6 || !name) return json({ error: 'Nome, e-mail e senha de 6 caracteres são obrigatórios' }, 400); if (db.users.some((item) => item.email === email)) return json({ error: 'E-mail já cadastrado' }, 409); const user = { id: createId('usr'), name, email, passwordHash: hashPassword(password), role: 'USER' as const, reputationScore: 0, createdAt: new Date().toISOString() }; db.users.push(user); await writeDb(db); return json({ user: publicUser(user), accessToken: signToken(user.id), refreshToken: signToken(user.id, 60 * 60 * 24 * 30) }, 201); }
  if(first==='auth'&&id==='business-register'){const email=String(data.email??'').trim().toLowerCase();const password=String(data.password??'');const name=String(data.name??'').trim();if(!email||password.length<6||!name)return json({error:'Responsável, e-mail e senha de 6 caracteres são obrigatórios'},400);if(db.users.some(item=>item.email===email))return json({error:'E-mail já cadastrado'},409);const user={id:createId('usr'),name,email,phone:String(data.phone??''),passwordHash:hashPassword(password),role:'BUSINESS' as const,reputationScore:0,createdAt:new Date().toISOString()};db.users.push(user);await writeDb(db);return json({user:publicUser(user),accessToken:signToken(user.id),refreshToken:signToken(user.id,60*60*24*30)},201)}
  if(first==='auth'&&id==='business-login'){const user=db.users.find(item=>item.email===String(data.email??'').trim().toLowerCase()&&item.role==='BUSINESS');if(!user||!verifyPassword(String(data.password??''),user.passwordHash))return json({error:'E-mail ou senha de parceiro inválidos'},401);return json({user:publicUser(user),accessToken:signToken(user.id),refreshToken:signToken(user.id,60*60*24*30)})}
  if (first === 'auth' && id === 'login') { const user = db.users.find((item) => item.email === String(data.email ?? '').trim().toLowerCase()); if (!user || !verifyPassword(String(data.password ?? ''), user.passwordHash)) return json({ error: 'E-mail ou senha inválidos' }, 401); return json({ user: publicUser(user), accessToken: signToken(user.id), refreshToken: signToken(user.id, 60 * 60 * 24 * 30) }); }
  if (first === 'auth' && id === 'refresh') { const refreshUserId = requestUserId(request); return refreshUserId ? json({ accessToken: signToken(refreshUserId) }) : unauthorized(); }
  if (!userId) return unauthorized();
  if (first === 'places' && !id) { const place = { ...data, id: createId('plc'), name: String(data.name ?? 'Novo Ponto Akolá'), createdByUserId: userId, status: 'PENDING', ownershipStatus: 'UNCLAIMED', partnerTier: 'COMMUNITY', createdAt: new Date().toISOString() }; db.places.push(place); await writeDb(db); return json(place, 201); }
  if (first === 'places' && id && third === 'confirmations') { const confirmation = { ...data, id: createId('cnf'), placeId: id, userId, createdAt: new Date().toISOString() }; db.confirmations.push(confirmation); await writeDb(db); return json(confirmation, 201); }
  if (first === 'places' && id && third === 'reviews') { const review = { ...data, id: createId('rev'), placeId: id, userId, createdAt: new Date().toISOString() }; db.reviews.push(review); await writeDb(db); return json(review, 201); }
  if (first === 'places' && id && third === 'claim') { const claim = { ...data, id: createId('clm'), placeId: id, userId, status: 'PENDING', createdAt: new Date().toISOString() }; db.claims.push(claim); await writeDb(db); return json(claim, 201); }
  if (first === 'places' && id && third === 'route-start') { const visit = { id: createId('vst'), placeId: id, userId, source: data.source ?? 'APP', routeStartedAt: new Date().toISOString() }; db.visits.push(visit); await writeDb(db); return json(visit, 201); }
  if (first === 'places' && id && third === 'check-in') { const visit = { id: createId('vst'), placeId: id, userId, source: 'CHECK_IN', validatedAt: new Date().toISOString() }; db.visits.push(visit); await writeDb(db); return json(visit, 201); }
  if (first === 'favorites' && id) { if (!db.favorites.some((item) => item.userId === userId && item.placeId === id)) db.favorites.push({ id: createId('fav'), userId, placeId: id, createdAt: new Date().toISOString() }); await writeDb(db); return json({ favorited: true }, 201); }
  if (first === 'offers' && id && third === 'redeem') { const redemption = { id: createId('rdm'), offerId: id, userId, placeId: data.placeId, redeemedAt: new Date().toISOString() }; db.redemptions.push(redemption); await writeDb(db); return json(redemption, 201); }
  if(first==='business'&&id==='claim'){const account=db.users.find(item=>item.id===userId);if(account?.role!=='BUSINESS')return businessRequired();const place=db.places.find(item=>item.id===String(data.placeId??''));if(!place)return json({error:'Estabelecimento não encontrado'},404);if(place.ownerUserId&&place.ownerUserId!==userId)return json({error:'Este perfil já foi reivindicado'},409);place.ownerUserId=userId;place.ownershipStatus='CLAIMED';place.partnerTier=place.partnerTier==='PARTNER'?'PARTNER':'VERIFIED';const claim={id:createId('clm'),placeId:place.id,userId,status:'APPROVED',createdAt:new Date().toISOString()};db.claims.push(claim);await writeDb(db);return json({claim,place},201)}
  if (first === 'reports' || (first === 'places' && id && third === 'reports')) { const report = { ...data, id: createId('rpt'), placeId: id ?? String(data.placeId ?? ''), userId, status: 'OPEN', createdAt: new Date().toISOString() }; db.reports.push(report); await writeDb(db); return json(report, 201); }
  if (first === 'business' && id === 'offers') { const account=db.users.find(item=>item.id===userId);if(account?.role!=='BUSINESS'&&account?.role!=='ADMIN')return businessRequired();const owned=db.places.find(item=>item.ownerUserId===userId);if(!owned)return json({error:'Reivindique um estabelecimento primeiro'},409);const offer = { ...data, id: createId('off'), placeId: owned.id, status: String(data.status??'ACTIVE') }; db.offers.push(offer); await writeDb(db); return json(offer, 201); }
  return json({ error: 'Rota não encontrada' }, 404);
}

export async function PUT(request: Request, context: { params: Promise<{ path: string[] }> }) {
  const parts = await pathParts(context.params); const db = await readDb(); const data = await body(request); const userId = requestUserId(request); if (!userId) return unauthorized(); const [first, id, third] = parts;
  if (first === 'places' && id) { const index = db.places.findIndex((item) => item.id === id); if (index < 0) return json({ error: 'Local não encontrado' }, 404); db.places[index] = { ...db.places[index], ...data, id }; await writeDb(db); return json(db.places[index]); }
  if (first === 'reviews' && id) { const review = db.reviews.find((item) => item.id === id && item.userId === userId); if (!review) return json({ error: 'Avaliação não encontrada' }, 404); Object.assign(review, data); await writeDb(db); return json(review); }
  if (first === 'business' && id === 'place') { const account=db.users.find(item=>item.id===userId);if(account?.role!=='BUSINESS'&&account?.role!=='ADMIN')return businessRequired();const place = db.places.find((item) => item.ownerUserId === userId); if (!place) return json({ error: 'Estabelecimento não encontrado' }, 404); Object.assign(place, data,{id:place.id,ownerUserId:userId}); await writeDb(db); return json(place); }
  if (first === 'business' && id === 'offers' && third) { const offer = db.offers.find((item) => item.id === third); if (!offer) return json({ error: 'Oferta não encontrada' }, 404); Object.assign(offer, data); await writeDb(db); return json(offer); }
  if (first === 'admin') { const user = db.users.find((item) => item.id === userId); if (user?.role !== 'ADMIN') return json({ error: 'Acesso administrativo necessário' }, 403); const collection = id === 'reports' ? db.reports : id === 'claims' ? db.claims : id === 'places' ? db.places : null; const item = collection?.find((entry) => entry.id === third); if (!item) return json({ error: 'Registro não encontrado' }, 404); Object.assign(item, data); await writeDb(db); return json(item); }
  return json({ error: 'Rota não encontrada' }, 404);
}

export async function DELETE(request: Request, context: { params: Promise<{ path: string[] }> }) {
  const parts = await pathParts(context.params); const db = await readDb(); const userId = requestUserId(request); if (!userId) return unauthorized(); const [first, id] = parts;
  if (first === 'favorites' && id) { db.favorites = db.favorites.filter((item) => !(item.userId === userId && item.placeId === id)); await writeDb(db); return new NextResponse(null, { status: 204 }); }
  if (first === 'reviews' && id) { db.reviews = db.reviews.filter((item) => !(item.id === id && item.userId === userId)); await writeDb(db); return new NextResponse(null, { status: 204 }); }
  return json({ error: 'Rota não encontrada' }, 404);
}
